// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCELO09gf8Xd8-xMGIQcWKSGthGEAMPwp8',
    appId: '1:394843781111:web:0bf0a620ba08e540caa0f2',
    messagingSenderId: '394843781111',
    projectId: 'flutter-midterm-bc46a',
    authDomain: 'flutter-midterm-bc46a.firebaseapp.com',
    databaseURL: 'https://flutter-midterm-bc46a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-midterm-bc46a.firebasestorage.app',
    measurementId: 'G-KD37TZ6C8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmz7kEEHPzpQx6Y2hchuLmMIei_Bvrlw',
    appId: '1:394843781111:android:243c920def621f7bcaa0f2',
    messagingSenderId: '394843781111',
    projectId: 'flutter-midterm-bc46a',
    databaseURL: 'https://flutter-midterm-bc46a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-midterm-bc46a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdARCBfdmOzd8W1GizPSkJXmJ8XT9_3_M',
    appId: '1:394843781111:ios:930019ecb7d4ea5dcaa0f2',
    messagingSenderId: '394843781111',
    projectId: 'flutter-midterm-bc46a',
    databaseURL: 'https://flutter-midterm-bc46a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-midterm-bc46a.firebasestorage.app',
    iosBundleId: 'com.example.dntMidterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdARCBfdmOzd8W1GizPSkJXmJ8XT9_3_M',
    appId: '1:394843781111:ios:930019ecb7d4ea5dcaa0f2',
    messagingSenderId: '394843781111',
    projectId: 'flutter-midterm-bc46a',
    databaseURL: 'https://flutter-midterm-bc46a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-midterm-bc46a.firebasestorage.app',
    iosBundleId: 'com.example.dntMidterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCELO09gf8Xd8-xMGIQcWKSGthGEAMPwp8',
    appId: '1:394843781111:web:cd789a92fe3e9465caa0f2',
    messagingSenderId: '394843781111',
    projectId: 'flutter-midterm-bc46a',
    authDomain: 'flutter-midterm-bc46a.firebaseapp.com',
    databaseURL: 'https://flutter-midterm-bc46a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-midterm-bc46a.firebasestorage.app',
    measurementId: 'G-SR149LFYJ2',
  );
}
